### ISSUE TITLE
I couldn't build

### ISSUE THREAD

**Issue by goodgene** [mzheravin/exchange-core#1]
Hello, 

First thanks for your contribution!
Actually I got the code from git, and tried to build, but failed. 

Could you check the build status in clean workspace?

Thanks. :)

***************************
APPLICATION FAILED TO START
***************************

Description:

Field resultsConsumer in org.openpredict.exchange.core.ExchangeCore required a bean of type 'java.util.function.Consumer' that could not be found.

Action:

Consider defining a bean of type 'java.util.function.Consumer' in your configuration.

**Comment by adrianog** [comment]
Is this working at all? 
thanks!

**Comment by liguifan** [comment]
This package looks awesome! Appreciate your contribution. However it looks like it couldn't be built.

**Comment by dendisuhubdy** [comment]
```
mvn clean verify
```

**Comment by bsouthallliquidnet** [comment]
I am still getting the issue where the application fails to start.

**Comment by scottjbarr** [comment]
java.util.function.Consumer was added in Java 1.8, but I still see the issue with 1.9 and 1.10.

The tests all pass, but I can't start the main. 

Adding plugin config to allow running the main...

```
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.0.2</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration>
                    <mainClass>org.openpredict.exchange.ExchangeCoreApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

Then running 

```
mvn exec:java
```

results in 

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field resultsConsumer in org.openpredict.exchange.core.ExchangeCore required a bean of type 'java.util.function.Consumer' that could not be found.


Action:

Consider defining a bean of type 'java.util.function.Consumer' in your configuration.
```

**Comment by fr0z3nfyr** [comment]
I just wish somebody could be kind enough to take out time to write a proper wiki with:
1. Build process
2. Start process
3. REST API
4. Using sample source etc.
5. Known issues / work around(s)
6. Other developer docs
7. ...

I understand if it looks like I'm being an a$$ for asking so much from an opensource project where I'm not even contributing. I'm sorry if I really am being one. 

I just thought it would help more people interested in this project to contribute here by referring to the wiki/docs instead of having to read through the code and figure out. I believe that no dev docs and no wiki could be one reason for so few contributors (technically, none except @mzheravin) on this seemingly excellent project.

**Comment by mzheravin** [comment]
Hi, 
Please have a look into recent README.md
I've stated documenting the project... First step is a usage example.
