### ISSUE TITLE
Pending balance and some logic bugs

### ISSUE THREAD

**Issue by buiminhhuy** [mzheravin/exchange-core#11]
I think you are missing for holding balance:
1. for action ASK, you will pending size of quote currency, but for action BID, you must be pending size * price of base currency.
2. for market order, when action ASK like as above, but for action BID, how to choose the price for holding base currency = size * ?price

Thanks,
Huy Bui.

**Comment by mzheravin** [comment]
Hello,
Yes you right. Risk control in the exchange mode is not implemented properly yet. Thanks for finding that.
Please feel free to create PR with your corrections. I think simple fix (but not very correct) would be to fix `pendingAmount` calculation here by conditionally taking from `lastAskPriceCache` (which actually has to be renamed to lastPriceCache):
                if (prSpec.baseCurrency == currency) {
                    pendingAmount += portfolioRecord.pendingSellSize;
                } else if (prSpec.quoteCurrency == currency) {
                    pendingAmount += portfolioRecord.pendingBuySize;
                }

From the top of my mind more correct design would be something like that:
- I start with answering for your question 2 - true, we can not let pure MARKET BUY order to go into matching section because there is always possibility that execution will lead to the negative balance. Lets disallow market orders in the exchange core. Instead we can define Immediate or Cancel (IoC) type of limit orders. Market orders can be converted into this type by gateway - some reasonable limit price can be automatically calculated based on last bbo prices, volatility, depth, free margin, etc.
- Just like you suggested - don't hold pending size, let's hold pending amount (in quote currency) instead. We just need to separate SymbolProtfolioRecord.java in two different implementations (exchange mode vs margin mode).
- Every time we receive order filling/rejection/cancellation we want to unhold precise amount. So we would need to add a new field `takerHoldPrice` into takeMatcherTradeEvent.java - that would allow risk engine to calculate exact frozen amount for the order.

As soon as I finish with persistence part, I will do these changes described above.
