### ISSUE TITLE
Exception in thread "Thread-x" java.lang.IllegalStateException: Thread is already running

### ISSUE THREAD

**Issue by buiminhhuy** [mzheravin/exchange-core#14]
Hi @mzheravin 
I am running test cases for checking new concepts from new changes, but I always get error as in attachment image?

![image](https://user-images.githubusercontent.com/568664/60428998-4d3b5300-9c24-11e9-84ad-a13b3d4b2cf6.png)

Another question,
In ExchangeCore class when place an order I hold balance by **orderAmount** (in below image), after that matcher trade I un-hold by handling in "handlerRiskRelease" after callback **resultConsumer**. It is always delay (it is waiting for new summit order), so it cannot release un-hold **orderAmount** this here, and So I handled un-hold **orderAmount** in **resultConsumer**.
![image](https://user-images.githubusercontent.com/568664/60429599-98099a80-9c25-11e9-8cad-44b1be0cfafb.png)

**Comment by mzheravin** [comment]
Hi @buiminhhuy 
Exception in the log - this is normal. There was a bug in Disruptor DSL. It creates more handlers than it should create. Fortunately there is protection preserves from starting same handlers second time, just throwing an exception without affecting rest of the code. My fix was merged, but new version of Disruptor was not released yet.

**Comment by mzheravin** [comment]
Sorry, I not sure I can understand your second question.

Some facts (assume symbols in exchange mode):
At risk-hold stage - whole order amount is gone from the account (-orderAmount).
For IoC order there is no any delay - one or more events (TRADE or REJECT) with same total volume are always created and attached to the same PlaceOrder message.
In risk-release stage user will get funds back (original or exchanged, or combination of them).
Result consumer handled in parallel with risk-release stage. So in theory user can submit second transaction after receiving positive result of first and then receive NSF (even he did not expect that) because risk release did not processed risk yet for first transaction. But in practice there is a threshold 10 microsecond (currently hardcoded) after which  all pending risk release operations are flushed by first incoming command.

**Comment by buiminhhuy** [comment]
Yes @mzheravin, you understood my second question. Thanks you for answer. Maybe, I am using old version, or debuging. Your framework really awesome for me.

**Comment by buiminhhuy** [comment]
I pulled source LMAX Disruptor and run test cases pass this issue. Thanks @mzheravin.
