### ISSUE TITLE
Access custom balance, symbols, users . What should I do?

### ISSUE THREAD

**Issue by prFor** [mzheravin/exchange-core#58]
I already have this user, balance, order. I just want to use match.
1. Use custom balance management
2. Use a custom user architecture
3. Use custom currency symbol management
thank you.

**Comment by mzheravin** [comment]
Hi,
You need to disable risk control (riskProcessingMode=NO_RISK_PROCESSING).
You also have to dynamically create users in the exchange core (having empty balances).
For symbols, you need to properly map symbol parameters in CoreSymbolSpecification, because the matching engine needs it for conversion between decimal and integers.
