### ISSUE TITLE
Where is MatcherEventType.CANCEL?

### ISSUE THREAD

**Issue by pooyakn** [mzheravin/exchange-core#88]
Hi,

I'm trying to update ```gateway-exchange-rest``` code to the latest version, but it seems a lot of things have changed.

I wish there were some sort of documentation explaining how the system works?
Is there some sort of draft that I can work on? In #62 you mentioned you are working on one.

Thanks.

**Comment by mzheravin** [comment]
Hello,
gateway-exchange-rest is very outdated.
There is no need for CANCEL event, only REDUCE that contains unmatched size of cancelled order.

**Comment by pooyakn** [comment]
So you suggest I abandon gateway-exchange-rest project and write a new one?

Thanks.
So If an order is partially filled, reduce event contains number of unfilled lots? and if reduce lots are equal to original order lots, order is not filled at all?

Also there was a part that checked if activeOrderId === cmd.orderId to determine if it's taker or maker order.
How is that determined here?

**Comment by mzheravin** [comment]
> So you suggest I abandon gateway-exchange-rest project and write a new one?
You can check basic principles from there.

> So If an order is partially filled, reduce event contains number of unfilled lots? and if reduce lots are equal to original order lots, order is not filled at all?
Exactly. Reduce event contains size that will subtracted  from the order. For example:
- Orignal GTC order size was 10.
- Then it was matched with another order so that now its remaining size is 4 - you will get Trade event with size=6
- Then if trader decides cancel that order, you will get reduce event with size=4. If it was never traded, you would receive 10.

> Also there was a part that checked if activeOrderId === cmd.orderId to determine if it's taker or maker order.
> How is that determined here?
Because taker is always the one who sent the command that triggeed a trade (no matter if it is was placing new order, or moving existing one) - you can just get orderId from the command. This was just an optimisation for reduce memory footprint for latency-critical scenarios (because all events had same Taker OrderId and same Taker UID).
